keys:
    - &admin_brian age1fn6c3gvsmjxpqk9hf9ye863d4rtcwqvq57wax2m7tg3t4ls84vaqtyv759
    - &host_nubes age1jwxydusswgeq8wvd8lzrlup4ttqwd39k243ev77crlkmkmf0sfqsq3q6lu
    - &host_caelus age17hk8tccd9a8sg875mqe6llw3euthjf8wlcmhlhk7lxlhmggvp92sfdstm5
    - &host_arcadia age1tvd5txsy62uywunnnyrhncdydnmgmg6prjczktw8f68wqun9kqysvuf94h
    - &host_minerva age1q8rtws7wsgrq5p7f5kxm6fhgtpfwtv5643geskn4euwfgeqkdeaqpd7mst
    - &host_argus age1y223rcmg932fe5tktywh7kylsrm4f9t9zxdnrwy5k32gryp4qf6s9cx5zx
creation_rules:
    - path_regex: ^secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
    - path_regex: ^modules/users/[^/]+/[^/]+\.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_nubes
                - *host_caelus
                - *host_arcadia
                - *host_minerva
                - *host_argus
    - path_regex: ^hosts/arcadia/secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_arcadia
    - path_regex: ^hosts/argus/secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_argus
    - path_regex: ^hosts/caelus/secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_caelus
    - path_regex: ^hosts/minerva/secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_minerva
    - path_regex: ^hosts/nubes/secrets.yaml$
      key_groups:
          - age:
                - *admin_brian
                - *host_nubes
