keys:
  - &mini1-yk age1yubikey1qtnxagsj9cfp5x79kqx8hsu58pc89w34xfrx0ykyzs7elvg2f8qucf3lgq3
  - &mini2-yk age1yubikey1q026af8ppajk7a9rc6srp6wdytdfyfydsdv33lemut8h20aq35ezshapaae
  - &key1-yk age1yubikey1qttm8ts9w5cyqwmpld45yftng8hsmfdt9k42pzz2leq8a7svvya3qlu9n8r
  - &key2-yk age1yubikey1qt0fu7u6uretapny90pzqll47hxc2edz8lduhy6ztlmgu9ffdjja2l63au9
  - &key3-yk age1yubikey1qvlquhc759rh69usa4dptw0rkcn0m6cghrz3j2f8064nfgag7anmqlfcsf2
  - &key4-yk age1yubikey1qwvfvqhvauv2tksrkh9yzhskeeznvk9hdtdvqmf6shlfj6k4phlqyhavea9
creation_rules:
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
    - age:
      - *mini1-yk
      - *mini2-yk
      - *key1-yk
      - *key2-yk
      - *key3-yk
      - *key4-yk
  - path_regex: modules/etcd-admin.yaml$
    key_groups:
    - age:
      - *joerg
      - *eva
      pgp:
      - *eve
  # https://github.com/carlpett/terraform-provider-sops does not support age keys yet
  - path_regex: eve/modules/gitlab/[^/]+\.enc.json$
    key_groups:
     - age:
      - *mini1-yk
      - *mini2-yk
      - *key1-yk
      - *key2-yk
      - *key3-yk
      - *key4-yk
  - path_regex: hosts/nixos/secrets/[^/]+\.yaml$
    key_groups:
     - age:
      - *mini1-yk
      - *mini2-yk
      - *key1-yk
      - *key2-yk
      - *key3-yk
      - *key4-yk
