* Installing to a new machine

For a new server start by determining the correct Hardware configuration for the box.

Three are a number of tools to help in this area but the one that allows for the easiest transition to Nixos is of course a Nixos image.

[[https://github.com/nix-community/nixos-images][nixos-images]] provides the small kexec image. Start by logging into the remote server and run the following 2 commands:


#+begin_src sh
curl -L https://github.com/nix-community/nixos-images/releases/download/nixos-unstable/nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz | tar -xzf- -C /root

/root/kexec/run

#+end_src

Once complete log back into the device and collect the device configuration

#+begin_src sh
nixos-generate-config --no-filesystems --root /mnt

ls -al /mnt/etc/nixos/
#+end_src

use [[https://github.com/nix-community/disko][disko]] to define the disk partitioning scheme that you with to apply and add the server to the list of hosts.

Add the sops components that are needed to the relevant secrets.yaml files.
Start by adding the new devices key to the .sops.yaml file. run one of the following commands to add the ssh-key as a reference.

#+begin_src sh
ssh-keyscan SERVER | ssh-to-age
cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
#+end_src

#+begin_src sh
sops hosts/SERVER/secrets.yaml
#+end_src

Then ensure to update all common secret files. Any time that a new key is added to sops this is required to be run.

#+begin_src sh
sops updatekeys secrets.yaml
sops updatekeys users/bmg-secrets.yaml
sops updatekeys hosts/HOSTNAME/secrets.yaml
#+end_src

Finally deploy the configuration to the new server
#+begin_src sh
nix run github:nix-community/nixos-anywhere -- --flake .#{server-config} --copy-host-keys root@<IP address>
#+end_src

Running this again will reset the server back to the state defined in the configuration, including wiping and recreating the disp partitioning scheme.

For day-to-day iterative updates use the following

#+begin_src shell
nixos-rebuild switch --flake .#{config}e --target-host "root@IP ADDR"
#+end_src
